In [3]:
pip install numpy --user


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------------------------------ --------- 9.7/12.6 MB 46.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 41.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [23]:
pip install pandas --user

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ----------------------- ---------------- 6.8/11.5 MB 38.1 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 35.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [24]:
import pandas as pd


In [21]:
import numpy as np

In [6]:
Q = np.empty((9,9))
Q[:] = np.nan

In [7]:
Q

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [8]:
Q[0,[0,1,3]] = 0
Q[1,[0,1,2,4]] = 0
Q[2,[1,2,5]] = 0
Q[3,[0,3,4]] = 0
Q[4,[1,3,4,5,7]] = 0
Q[5,[2,4,5,8]] = 0
Q[6,[3,6,7]] = 0
Q[7,[4,6,7,8]] = 0
Q[8,[5,7,8]] = 0

In [9]:
Q


array([[ 0.,  0., nan,  0., nan, nan, nan, nan, nan],
       [ 0.,  0.,  0., nan,  0., nan, nan, nan, nan],
       [nan,  0.,  0., nan, nan,  0., nan, nan, nan],
       [ 0., nan, nan,  0.,  0., nan, nan, nan, nan],
       [nan,  0., nan,  0.,  0.,  0., nan,  0., nan],
       [nan, nan,  0., nan,  0.,  0., nan, nan,  0.],
       [nan, nan, nan,  0., nan, nan,  0.,  0., nan],
       [nan, nan, nan, nan,  0., nan,  0.,  0.,  0.],
       [nan, nan, nan, nan, nan,  0., nan,  0.,  0.]])

In [10]:
R = Q
idx = np.isnan(R[:,4])
R[~idx,4] =-1
idx = np.isnan(R[:,8])
R[~idx,8] = 1

In [11]:
R


array([[ 0.,  0., nan,  0., nan, nan, nan, nan, nan],
       [ 0.,  0.,  0., nan, -1., nan, nan, nan, nan],
       [nan,  0.,  0., nan, nan,  0., nan, nan, nan],
       [ 0., nan, nan,  0., -1., nan, nan, nan, nan],
       [nan,  0., nan,  0., -1.,  0., nan,  0., nan],
       [nan, nan,  0., nan, -1.,  0., nan, nan,  1.],
       [nan, nan, nan,  0., nan, nan,  0.,  0., nan],
       [nan, nan, nan, nan, -1., nan,  0.,  0.,  1.],
       [nan, nan, nan, nan, nan,  0., nan,  0.,  1.]])

In [30]:
MAXITER = 1000
NUMSTATE = 9
eta = 0.99
for k in range(MAXITER):
    alpha = 1 /(k+1)
    Q2 = Q.copy()
    pk = 1 - (10/(20+k))
    selectMax = False
    if np.random.rand() < pk:
        selectMax = True
    for i in range(NUMSTATE):
        idx = np.isnan(R[i,:])
        allowedStates = np.arange(NUMSTATE)[~idx]
        j = Q[i,allowedStates].argmax()
        if selectMax:
            j = allowedStates[j]
        else:
            allowedStates = np.delete(allowedStates,j)
            j = np.random.permutation(allowedStates)[0]
        Q2[i,j] = (1 - alpha**k)*Q[i,j] + (alpha**k)*(R[i,j] +eta* np.nanmax(Q[j,:]))
    Q = Q2.copy()


In [31]:
Q

array([[ 9.20213814e-10,  1.09050209e-04,             nan,
         1.42927048e-33,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.12126654e-13,  2.47858573e-08,  1.23497949e-02,
                    nan, -9.99996738e-01,             nan,
                    nan,             nan,             nan],
       [            nan,  1.25471671e-08,  5.19021049e-02,
                    nan,             nan,  4.33265025e-01,
                    nan,             nan,             nan],
       [ 1.55060235e-07,             nan,             nan,
         3.57204179e-15, -9.99996738e-01,             nan,
                    nan,             nan,             nan],
       [            nan,  1.22262969e-11,             nan,
         6.58893774e-21, -9.99996727e-01,  4.10213356e-12,
                    nan,  3.87474091e-01,             nan],
       [            nan,             nan,  9.96434490e-09,
                    nan, -1.00000000e+00,  3.047920

In [32]:
i = 0
NUMTRANS = 10
for k in range(NUMTRANS):
    print(i)
    idx = np.isnan(Q[i,:])
    allowedStates = np.arange(9)[~idx]
    j = Q[i,allowedStates].argmax()
    j = allowedStates[j]
    i = j

0
1
2
5
8
8
8
8
8
8
